In [ ]:
# Task 17: Dataset Exploration

## Objective
Explore a dataset using Pandas to understand its dimensions,
columns, data types, summary statistics, and basic patterns
before machine-learning modelling.

## Dataset
Iris Dataset

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()

# Convert the dataset into a Pandas DataFrame
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Add the target species as a readable column
df["species"] = [
    iris.target_names[i] for i in iris.target
]

print("Dataset loaded successfully!")
print("Dataset name: Iris Dataset")

Dataset loaded successfully!
Dataset name: Iris Dataset

In [2]:
print("FIRST FIVE RECORDS")
display(df.head())

FIRST FIVE RECORDS

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [3]:
print("LAST FIVE RECORDS")
display(df.tail())

LAST FIVE RECORDS

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [4]:
print("DATASET DIMENSIONS")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Shape:", df.shape)

print("\nCOLUMN NAMES")
print(df.columns.tolist())

DATASET DIMENSIONS
Number of rows: 150
Number of columns: 5
Shape: (150, 5)

COLUMN NAMES
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'species']

In [5]:
print("DATASET INFORMATION")
df.info()

DATASET INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [6]:
print("SUMMARY STATISTICS")
display(df.describe())

SUMMARY STATISTICS

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [7]:
numerical_columns = df.select_dtypes(
    include="number"
).columns.tolist()

categorical_columns = df.select_dtypes(
    exclude="number"
).columns.tolist()

print("NUMERICAL COLUMNS")
print(numerical_columns)

print("\nCATEGORICAL COLUMNS")
print(categorical_columns)

NUMERICAL COLUMNS
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

CATEGORICAL COLUMNS
['species']

In [8]:
print("MISSING VALUES")
display(df.isnull().sum())

print("\nTOTAL MISSING CELLS")
print(df.isnull().sum().sum())

print("\nDUPLICATE ROWS")
print(df.duplicated().sum())

MISSING VALUES

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

TOTAL MISSING CELLS
0

DUPLICATE ROWS
1

In [9]:
print("SPECIES COUNTS")
display(df["species"].value_counts())

print("\nAVERAGE PETAL LENGTH BY SPECIES")
display(
    df.groupby("species")["petal length (cm)"]
      .mean()
      .round(2)
)

SPECIES COUNTS

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

AVERAGE PETAL LENGTH BY SPECIES

species
setosa        1.46
versicolor    4.26
virginica     5.55
Name: petal length (cm), dtype: float64

In [10]:
print("=" * 60)
print("DATASET EXPLORATION: KEY OBSERVATIONS")
print("=" * 60)

print(
    f"1. The dataset contains {df.shape[0]} rows "
    f"and {df.shape[1]} columns."
)

print(
    f"2. There are {len(numerical_columns)} numerical "
    f"columns and {len(categorical_columns)} categorical column."
)

print(
    f"3. The dataset contains "
    f"{df['species'].nunique()} distinct species."
)

print(
    f"4. The total number of missing cells is "
    f"{df.isnull().sum().sum()}."
)

print(
    f"5. The dataset contains "
    f"{df.duplicated().sum()} duplicate rows."
)

species_counts = df["species"].value_counts()

print("\nSpecies distribution:")
print(species_counts.to_string())

species_means = (
    df.groupby("species")["petal length (cm)"]
      .mean()
      .round(2)
)

print("\nAverage petal length by species:")
print(species_means.to_string())

highest_variation = (
    df[numerical_columns].std().idxmax()
)

print(
    f"\n6. '{highest_variation}' has the highest "
    "standard deviation among the numerical columns."
)

print("\nExploration completed successfully.")

============================================================
DATASET EXPLORATION: KEY OBSERVATIONS
============================================================
1. The dataset contains 150 rows and 5 columns.
2. There are 4 numerical columns and 1 categorical column.
3. The dataset contains 3 distinct species.
4. The total number of missing cells is 0.
5. The dataset contains 1 duplicate rows.

Species distribution:
species
setosa        50
versicolor    50
virginica     50

Average petal length by species:
species
setosa        1.46
versicolor    4.26
virginica     5.55

6. 'petal length (cm)' has the highest standard deviation among the numerical columns.

Exploration completed successfully.

In [11]:
df.to_csv("iris_dataset.csv", index=False)

print("Dataset exported as iris_dataset.csv")

Dataset exported as iris_dataset.csv

In [12]:
from google.colab import files

files.download("iris_dataset.csv")